# Google Cloud Build configuration for CI/CD

steps:
  # Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/slimpai-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/slimpai-backend:latest'
      - '-f'
      - 'Dockerfile.backend'
      - '.'

  # Build Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/slimpai-frontend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/slimpai-frontend:latest'
      - '-f'
      - 'Dockerfile.frontend'
      - '.'

  # Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/slimpai-backend'
    waitFor: ['build-backend']

  # Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/slimpai-frontend'
    waitFor: ['build-frontend']

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'slimpai-backend'
      - '--image=gcr.io/$PROJECT_ID/slimpai-backend:$SHORT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=300'
      - '--max-instances=10'
      - '--min-instances=0'
    waitFor: ['push-backend']

  # Get Backend URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'get-backend-url'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run services describe slimpai-backend \
          --region=${_REGION} \
          --format='value(status.url)' > /workspace/backend_url.txt
    waitFor: ['deploy-backend']

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$(cat /workspace/backend_url.txt)
        gcloud run deploy slimpai-frontend \
          --image=gcr.io/$PROJECT_ID/slimpai-frontend:$SHORT_SHA \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080 \
          --memory=1Gi \
          --cpu=1 \
          --timeout=300 \
          --max-instances=10 \
          --min-instances=0 \
          --set-env-vars="ADK_API_URL=$${BACKEND_URL}"
    waitFor: ['push-frontend', 'get-backend-url']

# Substitutions
substitutions:
  _REGION: 'us-central1'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/slimpai-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/slimpai-backend:latest'
  - 'gcr.io/$PROJECT_ID/slimpai-frontend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/slimpai-frontend:latest'

# Timeout for the entire build
timeout: '1800s'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
